### ISSUE TITLE
sparse_openmp failure with OMP_NUM_THREADS set to 1, 2, or 3 in spiluk streams test

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1859]
The `sparse_openmp` subtest `openmp.sparse_spiluk_double_int_size_t_TestExecSpace` fails with gcc/11.2 on SKX in debug build with `OMP_NUM_THREADS=1` or `OMP_NUM_THREADS=2` or `OMP_NUM_THREADS=3`:

```
[ RUN      ] openmp.sparse_spiluk_double_int_size_t_TestExecSpace
SEQLVLSCHD_RP
SEQLVLSCHD_TP1
SPILUKAlgorithm::SEQLVLSCHD_RP: 2 streams
  Stream 0: SEQLVLSCHD_RP
  Stream 1: SEQLVLSCHD_RP
SPILUKAlgorithm::SEQLVLSCHD_RP: 3 streams
Kokkos::abort: Instance has no resource allocated to it
Backtrace:
[0xbf2803] 
[0xbe8b08] 
[0xbe8b3b] 
[0x42de22] 
[0x605a47] 
[0x5781e0] 
[0x4d5f9a] 
[0x4567c4] 
[0x412062] 
[0xbc6d12] 
[0xbc29dc] 
[0xbaae3e] 
[0xbab5d0] 
[0xbabb9f] 
[0xbb2232] 
[0xbc7925] 
[0xbc36b6] 
[0xbb10e4] 
[0x40da16] 
[0x40d830] 
[0x7f73ece89555] __libc_start_main
[0x40d749] 
Aborted (core dumped)
```

I ran into this while working on a new build for Blake using the gcc/11.2.0 modules.
The test passes if I do not specify `OMP_NUM_THREADS` (in which case all threads available are used), and also passes if I set OMP_NUM_THREAD=4, 5, 8

The test does not fail in our nightly builds with gcc/10.2, 9.2, or 8.2 where we set `export KOKKOS_NUM_THREADS=8`

@vqd8a are you able to investigate?

Stack trace from gdb when run with 1 thread:
```
bash-4.2$ export OMP_NUM_THREADS=1
bash-4.2$ gdb --args ./sparse/unit_test/KokkosKernels_sparse_openmp --gtest_filter=openmp.sparse_spiluk_double_int_size_t_TestExecSpace

(gdb) bt
#0  0x00007ffff5fda387 in raise () from /lib64/libc.so.6
#1  0x00007ffff5fdba78 in abort () from /lib64/libc.so.6
#2  0x0000000000be8b40 in Kokkos::Impl::host_abort(char const*) ()
#3  0x000000000042de22 in Kokkos::abort(char const*) ()
#4  0x0000000000605a47 in std::vector<Kokkos::OpenMP, std::allocator<Kokkos::OpenMP> > Kokkos::Experimental::Impl::create_OpenMP_instances<int>(Kokkos::OpenMP const&, std::vector<int, std::allocator<int> > const&) ()
#5  0x00000000005780c4 in std::vector<Kokkos::OpenMP, std::allocator<Kokkos::OpenMP> > Kokkos::Experimental::partition_space<int, int>(Kokkos::OpenMP const&, int, int) ()
#6  0x00000000004d5f20 in void Test::run_test_spiluk_streams<double, int, unsigned long, Kokkos::OpenMP>(int, int) ()
#7  0x0000000000456799 in void test_spiluk_streams<double, int, unsigned long, Kokkos::OpenMP>() ()
#8  0x0000000000412062 in openmp_sparse_spiluk_double_int_size_t_TestExecSpace_Test::TestBody() ()
#9  0x0000000000bc6d12 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#10 0x0000000000bc29dc in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#11 0x0000000000baae3e in testing::Test::Run() ()
#12 0x0000000000bab5d0 in testing::TestInfo::Run() ()
#13 0x0000000000babb9f in testing::TestCase::Run() ()
#14 0x0000000000bb2232 in testing::internal::UnitTestImpl::RunAllTests() ()
#15 0x0000000000bc7925 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#16 0x0000000000bc36b6 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#17 0x0000000000bb10e4 in testing::UnitTest::Run() ()
#18 0x000000000040da16 in RUN_ALL_TESTS() ()
#19 0x000000000040d830 in main ()
```

**Reproducer** (blake testbed):
```bash
module purge
module load gcc/11.2.0 cmake/3.25.2 git netlib-lapack/3.10.1/gcc/11.2.0
module load openmpi/3.1.6/gcc/11.2.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --compiler=g++ --with-openmp --arch=SKX --debug --with-tpls=blas,lapack
```

Edit: The reproducer I posted was for a build using blas and lapack tpls, but the issue also occurs without tpls enabled

**Comment by vqd8a** [comment]
@ndellingwood I will look at it tomorrow.

**Comment by vqd8a** [comment]
@ndellingwood I think when ```OMP_NUM_THREADS``` is smaller than the desired number of streams, there is not enough resource for Kokkos to partition space. We can skip these stream tests in these cases. I can have a PR to fix this.
